// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertyIntelligence.Modules.Workflow.Infrastructure.Persistence;

#nullable disable

namespace PropertyIntelligence.Modules.Workflow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260723193404_InitialWorkflow")]
    partial class InitialWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.CompletionGateDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EvaluationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("evaluation_version");

                    b.Property<string>("FailureCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_message");

                    b.Property<string>("GateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gate_type");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<Guid>("WorkflowTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_task_id");

                    b.HasKey("Id")
                        .HasName("pk_completion_gate");

                    b.HasIndex("OrganizationId", "GateType")
                        .HasDatabaseName("ix_completion_gate_organization_id_gate_type");

                    b.HasIndex("WorkflowTaskId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ix_completion_gate_workflow_task_id_id");

                    b.ToTable("completion_gate", "workflow");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowBlocker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ResolutionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_reason");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("WorkflowTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_task_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_blocker");

                    b.HasIndex("WorkflowTaskId")
                        .HasDatabaseName("ix_workflow_blocker_workflow_task_id");

                    b.HasIndex("OrganizationId", "WorkflowTaskId", "ResolvedAt")
                        .HasDatabaseName("ix_workflow_blocker_organization_id_workflow_task_id_resolved_");

                    b.ToTable("workflow_blocker", "workflow");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("SnapshotSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_schema_version");

                    b.Property<Guid>("SourcePlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_playbook_id");

                    b.Property<Guid>("SourcePlaybookVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_playbook_version_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_instance");

                    b.HasIndex("OrganizationId", "ClaimId")
                        .HasDatabaseName("ix_workflow_instance_organization_id_claim_id");

                    b.HasIndex("OrganizationId", "SourcePlaybookVersionId")
                        .HasDatabaseName("ix_workflow_instance_organization_id_source_playbook_version_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_workflow_instance_organization_id_status");

                    b.ToTable("workflow_instance", "workflow");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("stage_order");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("skip_reason");

                    b.Property<DateTimeOffset?>("SkippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("skipped_at");

                    b.Property<Guid?>("SkippedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("skipped_by");

                    b.Property<Guid>("SourceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_definition_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_instance_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_stage");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_workflow_stage_organization_id_status");

                    b.HasIndex("WorkflowInstanceId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_stage_workflow_instance_id_stage_order");

                    b.HasIndex("WorkflowInstanceId", "SourceDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_stage_workflow_instance_id_source_definition_id");

                    b.ToTable("workflow_stage", "workflow");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("task_order");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("SourceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_definition_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_stage_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_task");

                    b.HasIndex("WorkflowStageId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_task_workflow_stage_id_task_order");

                    b.HasIndex("WorkflowStageId", "SourceDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_task_workflow_stage_id_source_definition_id");

                    b.HasIndex("OrganizationId", "Status", "AssignedTo")
                        .HasDatabaseName("ix_workflow_task_organization_id_status_assigned_to");

                    b.ToTable("workflow_task", "workflow");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowTaskDependency", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("DependencySourceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependency_source_definition_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("TaskId", "DependencySourceDefinitionId")
                        .HasName("pk_workflow_task_dependency");

                    b.HasIndex("OrganizationId", "DependencySourceDefinitionId")
                        .HasDatabaseName("ix_workflow_task_dependency_organization_id_dependency_source_");

                    b.ToTable("workflow_task_dependency", "workflow");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.CompletionGateDefinition", b =>
                {
                    b.HasOne("PropertyIntelligence.Modules.Workflow.Domain.WorkflowTask", null)
                        .WithMany("_completionGates")
                        .HasForeignKey("WorkflowTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_completion_gate_workflow_task_workflow_task_id");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowBlocker", b =>
                {
                    b.HasOne("PropertyIntelligence.Modules.Workflow.Domain.WorkflowTask", null)
                        .WithMany("_blockers")
                        .HasForeignKey("WorkflowTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_blocker_workflow_task_workflow_task_id");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowStage", b =>
                {
                    b.HasOne("PropertyIntelligence.Modules.Workflow.Domain.WorkflowInstance", null)
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_stage_workflow_instance_workflow_instance_id");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowTask", b =>
                {
                    b.HasOne("PropertyIntelligence.Modules.Workflow.Domain.WorkflowStage", null)
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_task_workflow_stage_workflow_stage_id");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowTaskDependency", b =>
                {
                    b.HasOne("PropertyIntelligence.Modules.Workflow.Domain.WorkflowTask", null)
                        .WithMany("_dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_task_dependency_workflow_task_task_id");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowInstance", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowStage", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PropertyIntelligence.Modules.Workflow.Domain.WorkflowTask", b =>
                {
                    b.Navigation("_blockers");

                    b.Navigation("_completionGates");

                    b.Navigation("_dependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
