version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /src/WebApi/PropertyIntelligence.Api
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /infrastructure
    schedule:
      interval: monthly
